### PR TITLE
Merging filter system changes into m4_integrate_main with other features

### PR DESCRIPTION
**Pull request by SandraV255**
Adding up-to-date code for filter system that is working with backend into integrate_main. Filter system now pulls restaurant data from table in backend SQLite database and accurately filters restaurant cards by price range, cuisine, vegetarian, and max distance (calculates distance from user-inputted location to each restaurant and displays only restaurants within the user's max distance preference).

### CODE REVIEW

**Review by aliyabedeen — APPROVED** [review]
The filter integration looks good. Good to merge!

**Review by evc29 — APPROVED** [review]
Looks good! Changes seem good, fix the merge conflict and you will be all set! Yay!

**Review by addie-p — APPROVED** [review]
Just need to resolve the merge conflict with the function in main.js, but otherwise looks good! Tested and works locally.

**Review by cding888 — APPROVED** [review]
looks good! nice work on the filter system, just fix the merge conflict!

**Review by helenliuf — APPROVED** [review]
Modified files look good, just be careful when fixing the merge conflict to not lose anything!

**Pull request merged**
