### PR TITLE
Merging Login Bug Fix (#172): Protected endpoints into Integrated Branch

### PR DESCRIPTION
**Pull request by addie-p**
Merging the fixed bug for login/authentication as described in Issue #172. The bug has been fixed and the endpoints are now protected so a user cannot access home pages without being authenticated first.

### CODE REVIEW

**Comment by evc29** [comment]
Looks great Addie, login works perfectly and I can't access other files without login like wanted. Everything looks good to merge! Great job!

**Review by evc29 — APPROVED** [review]
Looks great Addie, login works perfectly and I can't access other files without login like wanted. Everything looks good to merge! Great job!

**Review by jadatwo — APPROVED** [review]
Tested and correctly protects endpoints by requiring user to log in first. Looks good and ready to merge.

**Review by SandraV255 — APPROVED** [review]
This looks great to merge- login and authentication work as intended, thank you Addie!

**Review by cding888 — APPROVED** [review]
looks good addie! I pulled the code to my remote repository and login works as intended! Good to merge!

**Review by helenliuf — APPROVED** [review]
went over changes and everything looks good to merge into integrated branch for secure authentication!

**Pull request merged**
