### PR TITLE
Merging Geolocation_filter feature into m4_integrate_main

### PR DESCRIPTION
**Pull request by aliyabedeen**
This code implements the feature for M4 which Aliya and Sandra worked on. It allows users to choose their location from one of four towns: Northampton, Amherst, Hadley, or South Hadley. The feature pulls the latitude and longitude coordinates of each restaurant from the SQLite database to calculate the distance between the selected location and the restaurant. The user can filter restaurants by maximum distance from their chosen location. The cuisine, vegetarian, and price range filters are also updated to accurately filter the restaurants based on the data pulled from the database. Additionally, the mini-map is updated to zoom in on the user's selected location and display the filtered restaurants, with coordinates pulled from the filtered restaurants array. The feature is connected to a dropdown bar where users select their location.

### CODE REVIEW

**Review by evc29 — APPROVED** [review]
Sounds good but get rid of changes in .DS_Store! Thanks, good job guys!

**Review by addie-p — COMMENTED** [review]
Make sure to get rid of the changes in .DS_Store but looks good otherwise!

**Review by jadatwo — APPROVED** [review]
Approved because filter system works correctly but need to delete .DS_store files to resolve merge conflicts

**Comment by cding888** [comment]
looks good! just make sure to get rid of the merge conflicts in DS store!

**Review by cding888 — APPROVED** [review]
looks good! just make sure to get rid of the merge conflicts in DS store!

**Review by SandraV255 — APPROVED** [review]
Our implementation looks good- let's make sure to remove changes in .DS_Store but other than that should be all set!

**Pull request closed without merging**
