### PR TITLE
Rating System (#160): Pull m4 rating system into integrate main

### PR DESCRIPTION
**Pull request by jadatwo**
Integrate rating system m4 changes into integrate main. Retrieves and pulls data from backend to prepopulate data and store data as well. Allows user from restaurant dashboard to input their review and revisit it. Connects to photo uploads where the user can then input their photo and come back to rating system.

### CODE REVIEW

**Review by addie-p — COMMENTED** [review]
Looks good Jada, tested on my end and everything is functional! The rating system works as intended

**Review by evc29 — APPROVED** [review]
Looks good Jada, nice rating system changes. Everything works well!

**Review by cding888 — APPROVED** [review]
The rating system is functional and looks good! Looks good to merge!

**Review by aliyabedeen — APPROVED** [review]
Looks good friend! proud of you!

**Review by addie-p — APPROVED** [review]
Looks good Jada, tested on my end and everything is functional! The rating system works as intended

**Review by SandraV255 — APPROVED** [review]
Rating system back-end implementation looks great! Thanks Jada, good to merge

**Pull request merged**
