### PR TITLE
Merging authentication feature to integrate-main

### LINKED ISSUE #135: Connect login page to rest of website
After the user succesfully logs in, the page should switch to the main page of Dashboard where the user an then start finding their ideal restaurant.

### PR DESCRIPTION
**Pull request by cding888**
This code is implementing Addie and I's feature for M4, which is completing the authentication for users by implementing backend code that allows the user to register an account and login to their account. Users can register their username as long as it's not already taken, and they can login to their account with the username and password they just registered with. We are storing the registered username and passwords into a database when they register and fetching it when the user logs in to compare if it's a valid username and password. This ensures only valid username-password combinations are accepted. Adding reviewers for good github practices!

### CODE REVIEW

**Review by addie-p — APPROVED** [review]
The login and authentication pages look good! I pulled the code onto my remote repository to test the features and they function as intended - with the user's account information being updated in the SQLite database upon registration and the authentication working when the user hits "Log In". Looks good to merge!

**Review by jadatwo — APPROVED** [review]
allows user to authenticate login to store personal data, ensures validity of username and password combinations. looks good and ready to merge.

**Comment by helenliuf** [comment]
code functions as intended and properly allows personal users on the application, and works with rest of application structure. looks good to merge!

**Review by helenliuf — APPROVED** [review]

**Review by SandraV255 — APPROVED** [review]
This looks great- registration and login features work correctly. Username and password are stored in database and are able to retrieved for validation when the user attempts to log in. Feature looks all set to merge!

**Review by evc29 — APPROVED** [review]
Everything works correctly and looks good with register/login, good job guys!

**Review by aliyabedeen — APPROVED** [review]
The authentication looks great. Seems good to merge!

**Pull request merged**
